apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: app-gateway:latest
        imagePullPolicy: Never
        env:
        - name: RUST_LOG
          value: info
        - name: AUTH_SERVICE_URI
          value: http://auth:50051
        ports:
        - containerPort: 50051
          name: grpc
        livenessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 5
          periodSeconds: 10
