apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: app
  labels:
    app: auth
spec:
  type: LoadBalancer
  selector:
    app: auth
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
