apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: app
  labels:
    app: gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
